version: '3'

services:

  mysql-server:
    container_name: 'mysql-dabatase'
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports: 
      - '3306:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo

  redis-server:
    container_name: 'redis-database'
    image: 'redis'
    restart: always
    ports: 
      - '6379:6379'
